### ISSUE TITLE
stream Map Existing problem

### ISSUE THREAD

**Issue by lym169** [duke-git/lancet#161]
Currently, stream Map only supports conversions of the same type, but the practical application is more to map to different type slices
![PixPin_2024-01-22_09-42-38](https://github.com/duke-git/lancet/assets/65445971/d8765fd8-c9e0-46ba-b442-49e17c6ce68b)

**Comment by duke-git** [comment]
@lym169 This is because that go doesn't allow type parameters in methods. like below code snap
```go
func (s stream[T]) Map[U any](mapper func(item T) U) stream[U]
```
see [https://www.reddit.com/r/golang/comments/tvfbow/the_fact_that_methods_are_not_allowed_to_have/](https://www.reddit.com/r/golang/comments/tvfbow/the_fact_that_methods_are_not_allowed_to_have/)
[https://github.com/golang/go/issues/49085](https://github.com/golang/go/issues/49085)

**Comment by lym169** [comment]
Thank you,
This can be done with interface{}, but ultimately you need to specify the type of conversion
